version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10  # Gunakan Python 3.10
    working_directory: ~/project

jobs:
  scrape_data:
    executor: python-executor
    steps:
      - checkout  # Clone repo

      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            playwright install --with-deps chromium  # Install Chromium dan dependencies

      - run:
          name: Run Scraping Script
          command: python scrape.py

      - run:
          name: Compress Dataset to ZIP
          command: |
            apt-get update && apt-get install -y zip  # Pastikan zip terinstal
            zip -r dataset.zip dataset/

      - store_artifacts:
          path: dataset.zip
          destination: scraped_data.zip

workflows:
  version: 2
  scrape_workflow:
    jobs:
      - scrape_data
