name: Scrape Data from Example

on:
  schedule:
    - cron: '0 12 * * *'  # Menjalankan setiap hari pukul 12:00 UTC
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          pip install playwright beautifulsoup4 pycountry
          playwright install
          playwright install-deps

      - name: Run scraper
        run: python scraper/scrape.py

      - name: Find and List CSV Files
        run: |
          echo "Files in the dataset directory:"
          ls -lah dataset/

      - name: Upload Scraped Data
        uses: actions/upload-artifact@v4
        with:
          name: scraped-data
          path: dataset/*.csv  # Simpan semua file CSV hasil scraping
          retention-days: 7  # Simpan selama 7 hari
