name: Scrape Data from Example

on:
  schedule:
    - cron: '0 12 * * *'  # Menjalankan setiap hari pada pukul 12:00 UTC
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          pip install playwright
          playwright install
          playwright install-deps  # Menyediakan dependensi sistem yang diperlukan

      - name: Run scraper
        run: python scraper/scrape.py

      - name: Commit and Push Data
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/sandyartha/club-1.git
          git add scraped_data.json
          git commit -m "Update scraped data [$(date)]" || echo "No changes to commit"
          git push origin master

